// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package mobile

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mobile_MobileApp, InType: reflect.TypeOf(&MobileApp{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mobile_MobileAppList, InType: reflect.TypeOf(&MobileAppList{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mobile_MobileAppSpec, InType: reflect.TypeOf(&MobileAppSpec{})},
	)
}

// DeepCopy_mobile_MobileApp is an autogenerated deepcopy function.
func DeepCopy_mobile_MobileApp(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*MobileApp)
		out := out.(*MobileApp)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		return nil
	}
}

// DeepCopy_mobile_MobileAppList is an autogenerated deepcopy function.
func DeepCopy_mobile_MobileAppList(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*MobileAppList)
		out := out.(*MobileAppList)
		*out = *in
		if in.Items != nil {
			in, out := &in.Items, &out.Items
			*out = make([]MobileApp, len(*in))
			for i := range *in {
				if err := DeepCopy_mobile_MobileApp(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

// DeepCopy_mobile_MobileAppSpec is an autogenerated deepcopy function.
func DeepCopy_mobile_MobileAppSpec(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*MobileAppSpec)
		out := out.(*MobileAppSpec)
		*out = *in
		return nil
	}
}
