
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

# kuberentes 1.7 no official 1.7 branch created for this repo yet
[[constraint]]
  revision = "ab57ed5a72c3b67058f665d660e23bae18339fc2" 
  name = "k8s.io/apiserver"

[[constraint]]
  revision = "abe34e4f5b4413c282a83011892cbeea5b32223b"
  name = "k8s.io/apimachinery"  

[[constraint]]
  revision = "cc44961f935a644fb82c0f4b6591543704578db7"
  name = "k8s.io/client-go"  

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "9.0.0"
