// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	mobile "github.com/feedhenry/mobile-control-panel/server/pkg/apis/mobile"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_MobileApp_To_mobile_MobileApp,
		Convert_mobile_MobileApp_To_v1alpha1_MobileApp,
		Convert_v1alpha1_MobileAppList_To_mobile_MobileAppList,
		Convert_mobile_MobileAppList_To_v1alpha1_MobileAppList,
		Convert_v1alpha1_MobileAppSpec_To_mobile_MobileAppSpec,
		Convert_mobile_MobileAppSpec_To_v1alpha1_MobileAppSpec,
	)
}

func autoConvert_v1alpha1_MobileApp_To_mobile_MobileApp(in *MobileApp, out *mobile.MobileApp, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MobileAppSpec_To_mobile_MobileAppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MobileApp_To_mobile_MobileApp is an autogenerated conversion function.
func Convert_v1alpha1_MobileApp_To_mobile_MobileApp(in *MobileApp, out *mobile.MobileApp, s conversion.Scope) error {
	return autoConvert_v1alpha1_MobileApp_To_mobile_MobileApp(in, out, s)
}

func autoConvert_mobile_MobileApp_To_v1alpha1_MobileApp(in *mobile.MobileApp, out *MobileApp, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_mobile_MobileAppSpec_To_v1alpha1_MobileAppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_mobile_MobileApp_To_v1alpha1_MobileApp is an autogenerated conversion function.
func Convert_mobile_MobileApp_To_v1alpha1_MobileApp(in *mobile.MobileApp, out *MobileApp, s conversion.Scope) error {
	return autoConvert_mobile_MobileApp_To_v1alpha1_MobileApp(in, out, s)
}

func autoConvert_v1alpha1_MobileAppList_To_mobile_MobileAppList(in *MobileAppList, out *mobile.MobileAppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]mobile.MobileApp)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MobileAppList_To_mobile_MobileAppList is an autogenerated conversion function.
func Convert_v1alpha1_MobileAppList_To_mobile_MobileAppList(in *MobileAppList, out *mobile.MobileAppList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MobileAppList_To_mobile_MobileAppList(in, out, s)
}

func autoConvert_mobile_MobileAppList_To_v1alpha1_MobileAppList(in *mobile.MobileAppList, out *MobileAppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]MobileApp, 0)
	} else {
		out.Items = *(*[]MobileApp)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_mobile_MobileAppList_To_v1alpha1_MobileAppList is an autogenerated conversion function.
func Convert_mobile_MobileAppList_To_v1alpha1_MobileAppList(in *mobile.MobileAppList, out *MobileAppList, s conversion.Scope) error {
	return autoConvert_mobile_MobileAppList_To_v1alpha1_MobileAppList(in, out, s)
}

func autoConvert_v1alpha1_MobileAppSpec_To_mobile_MobileAppSpec(in *MobileAppSpec, out *mobile.MobileAppSpec, s conversion.Scope) error {
	out.ClientType = in.ClientType
	return nil
}

// Convert_v1alpha1_MobileAppSpec_To_mobile_MobileAppSpec is an autogenerated conversion function.
func Convert_v1alpha1_MobileAppSpec_To_mobile_MobileAppSpec(in *MobileAppSpec, out *mobile.MobileAppSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MobileAppSpec_To_mobile_MobileAppSpec(in, out, s)
}

func autoConvert_mobile_MobileAppSpec_To_v1alpha1_MobileAppSpec(in *mobile.MobileAppSpec, out *MobileAppSpec, s conversion.Scope) error {
	out.ClientType = in.ClientType
	return nil
}

// Convert_mobile_MobileAppSpec_To_v1alpha1_MobileAppSpec is an autogenerated conversion function.
func Convert_mobile_MobileAppSpec_To_v1alpha1_MobileAppSpec(in *mobile.MobileAppSpec, out *MobileAppSpec, s conversion.Scope) error {
	return autoConvert_mobile_MobileAppSpec_To_v1alpha1_MobileAppSpec(in, out, s)
}
